services:
  node-run:
    image: "node:23.7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/:/home/node/app/
    restart: always
    command: bash -c "node ."
    depends_on:
      - node-deploy
      - node-install
      - mongo
  node-deploy:
      image: "node:23.7"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./src/:/home/node/app/
      command: bash -c "node ./deploy-commands.js"
      depends_on:
        - node-install
  node-install:
    image: "node:23.7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/:/home/node/app/
    command: bash -c "npm install"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
      MONGODB_CONNSTRING: "${MONGODB_URI}"
    volumes:
      - ./db:/data/db
    command: mongod --auth --bind_ip_all